# -*- coding: utf-8 -*-
"""college_chatbot_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpekJCIjA8kR7Nl73JkFw3nfe9ik7TPp
"""

# college_chatbot_ml.py

import streamlit as st
import pandas as pd
import ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
import random

# Load and process data
@st.cache_data
def load_data_and_model():
    df = pd.read_csv("chatbot_training_data.csv")
    df['responses'] = df['responses'].apply(ast.literal_eval)

    X = df['text']
    y = df['intent']

    # Train model
    model = make_pipeline(TfidfVectorizer(), LogisticRegression())
    model.fit(X, y)

    # Create response map
    response_map = df.groupby('intent')['responses'].apply(list).to_dict()
    return model, response_map

model, response_map = load_data_and_model()

# Intent prediction and response
def get_response(user_input):
    intent = model.predict([user_input])[0]
    responses = sum(response_map.get(intent, [["Sorry, I didn't understand."]]), [])
    return random.choice(responses)

# Streamlit App UI
st.title("🎓 ML-powered College Enquiry Chatbot")
st.write("Ask about courses, fees, admission, or anything else!")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.text_input("You:", key="input")

if user_input:
    response = get_response(user_input)
    st.session_state.chat_history.append(("You", user_input))
    st.session_state.chat_history.append(("Bot", response))

for speaker, message in st.session_state.chat_history:
    st.markdown(f"**{speaker}:** {message}")