# -*- coding: utf-8 -*-
"""College enquiry chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uP01WwgpePkV349iAKOoJhkH1H-WRMs8

#**Project description**: The College Enquiry Chatbot is an AI-powered virtual assistant designed to provide instant answers to common questions from students and parents about a college. Built using Python and Streamlit, the chatbot uses a predefined set of intents and responses to handle queries related to college hours, admission procedures, courses offered, fee structure, and general information such as greetings and contact details.
"""

!pip install streamlit pyngrok --quiet

import streamlit as st
import pandas as pd
import random
import difflib
import ast

# Load and process data
@st.cache_data
def load_data():
    df = pd.read_csv("chatbot_training_data.csv")
    df['responses'] = df['responses'].apply(ast.literal_eval)
    return df

df = load_data()

# Response function with fuzzy matching
def get_response(user_input):
    best_match = None
    highest_score = 0
    for _, row in df.iterrows():
        score = difflib.SequenceMatcher(None, user_input.lower(), row['pattern'].lower()).ratio()
        if score > highest_score:
            highest_score = score
            best_match = row
    if highest_score > 0.6:
        return random.choice(best_match['responses'])
    return "Sorry, I didn't understand that."

# Setup Streamlit app
st.title("🏫 College Enquiry Chatbot")
st.write("Ask me anything about courses, fees, or admissions!")

# Maintain chat history using session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.text_input("You:", key="input")

if user_input:
    response = get_response(user_input)
    st.session_state.chat_history.append(("You", user_input))
    st.session_state.chat_history.append(("Bot", response))

# Display chat history
for speaker, message in st.session_state.chat_history:
    st.markdown(f"**{speaker}:** {message}")

from google.colab import files
uploaded = files.upload()

!ngrok config add-authtoken 2ywfVy7ARGbuCbtqlCs4A1aaGDj_3Nf5r85iye654zHNZNuFu

!pkill streamlit
!pkill ngrok
# ✅ Start ngrok tunnel and run Streamlit
from pyngrok import ngrok

public_url = ngrok.connect(8501, proto="http")
print("🚀 Streamlit app is live at:", public_url)

!streamlit run app.py &>/content/logs.txt &

