# -*- coding: utf-8 -*-
"""indexer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vuqv-pJ83Dx_v_ihExf6w493rSFY7xrY
"""

!pip install faiss-cpu -q

# indexer.py
import pandas as pd
import pickle
import faiss
from sentence_transformers import SentenceTransformer
import numpy as np

# Load your CSV (change path as needed)
df = pd.read_csv("/content/kcc_raw.csv").dropna(subset=["questions", "answers"])

questions = df["questions"].tolist()
answers = df["answers"].tolist()

# Embed questions
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(questions, show_progress_bar=True).astype("float32")

# Build FAISS index
index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)

# Save FAISS index
faiss.write_index(index, "faiss_index.index")

# Save questions and answers
with open("text_data.pkl", "wb") as f:
    pickle.dump({"questions": questions, "answers": answers}, f)

print("✅ Index and data saved successfully.")